/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UpdateArchivedStatus$Params {
  'book-id': number;
  connectedUser: 'RSA' | 'DSS' | 'aNULL' | 'DH' | 'ECDH' | 'KRB5' | 'ECDSA' | 'PSK' | 'GOST94' | 'GOST01' | 'FZA' | 'SRP' | 'ANY';
}

export function updateArchivedStatus(http: HttpClient, rootUrl: string, params: UpdateArchivedStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
  const rb = new RequestBuilder(rootUrl, updateArchivedStatus.PATH, 'patch');
  if (params) {
    rb.path('book-id', params['book-id'], {});
    rb.query('connectedUser', params.connectedUser, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: parseFloat(String((r as HttpResponse<any>).body)) }) as StrictHttpResponse<number>;
    })
  );
}

updateArchivedStatus.PATH = '/books/archived/{book-id}';
